EUROPEAN_LANGUAGE_SPECS = [
    {"code": "sq", "name": "Albanian", "lingua": "ALBANIAN"},
    {"code": "hy", "name": "Armenian", "lingua": "ARMENIAN"},
    {"code": "az", "name": "Azerbaijani", "lingua": "AZERBAIJANI"},
    {"code": "eu", "name": "Basque", "lingua": "BASQUE"},
    {"code": "be", "name": "Belarusian", "lingua": "BELARUSIAN"},
    {"code": "bs", "name": "Bosnian", "lingua": "BOSNIAN"},
    {"code": "bg", "name": "Bulgarian", "lingua": "BULGARIAN"},
    {"code": "ca", "name": "Catalan", "lingua": "CATALAN"},
    {"code": "hr", "name": "Croatian", "lingua": "CROATIAN"},
    {"code": "cs", "name": "Czech", "lingua": "CZECH"},
    {"code": "da", "name": "Danish", "lingua": "DANISH"},
    {"code": "nl", "name": "Dutch", "lingua": "DUTCH"},
    {"code": "en", "name": "English", "lingua": "ENGLISH"},
    {"code": "et", "name": "Estonian", "lingua": "ESTONIAN"},
    {"code": "fi", "name": "Finnish", "lingua": "FINNISH"},
    {"code": "fr", "name": "French", "lingua": "FRENCH"},
    {"code": "ka", "name": "Georgian", "lingua": "GEORGIAN"},
    {"code": "de", "name": "German", "lingua": "GERMAN"},
    {"code": "el", "name": "Greek", "lingua": "GREEK"},
    {"code": "hu", "name": "Hungarian", "lingua": "HUNGARIAN"},
    {"code": "is", "name": "Icelandic", "lingua": "ICELANDIC"},
    {"code": "ga", "name": "Irish", "lingua": "IRISH"},
    {"code": "it", "name": "Italian", "lingua": "ITALIAN"},
    {"code": "lv", "name": "Latvian", "lingua": "LATVIAN"},
    {"code": "lt", "name": "Lithuanian", "lingua": "LITHUANIAN"},
    {"code": "mk", "name": "Macedonian", "lingua": "MACEDONIAN"},
    {"code": "nb", "name": "Norwegian Bokmal", "lingua": "BOKMAL"},
    {"code": "nn", "name": "Norwegian Nynorsk", "lingua": "NYNORSK"},
    {"code": "pl", "name": "Polish", "lingua": "POLISH"},
    {"code": "pt", "name": "Portuguese", "lingua": "PORTUGUESE"},
    {"code": "ro", "name": "Romanian", "lingua": "ROMANIAN"},
    {"code": "ru", "name": "Russian", "lingua": "RUSSIAN"},
    {"code": "sr", "name": "Serbian", "lingua": "SERBIAN"},
    {"code": "sk", "name": "Slovak", "lingua": "SLOVAK"},
    {"code": "sl", "name": "Slovene", "lingua": "SLOVENE"},
    {"code": "es", "name": "Spanish", "lingua": "SPANISH"},
    {"code": "sv", "name": "Swedish", "lingua": "SWEDISH"},
    {"code": "tr", "name": "Turkish", "lingua": "TURKISH"},
    {"code": "uk", "name": "Ukrainian", "lingua": "UKRAINIAN"},
    {"code": "cy", "name": "Welsh", "lingua": "WELSH"},
]

SUPPORTED_LANGUAGE_CODES = tuple(spec["code"] for spec in EUROPEAN_LANGUAGE_SPECS)
LANGUAGE_NAME_BY_CODE = {spec["code"]: spec["name"] for spec in EUROPEAN_LANGUAGE_SPECS}
LINGUA_ENUM_BY_CODE = {spec["code"]: spec["lingua"] for spec in EUROPEAN_LANGUAGE_SPECS}

# Only use characters or scripts that are strong enough to decide immediately.
UNIQUE_CHAR_LANGUAGE_HINTS = {
    "uk": "їєґ",
    "be": "ў",
    "pl": "łńśźż",
    "cs": "ř",
    "sk": "ľĺô",
    "lt": "ėų",
    "lv": "ģķļņ",
    "ro": "ăâîșț",
    "de": "ß",
    "ca": "·",
    "mk": "ѓќѕ",
    "sr": "ђћ",
    "az": "ə",
}

LEXICAL_LANGUAGE_HINTS = {
    "en": (
        "hello",
        "hi",
        "friend",
        "thanks",
        "please",
        "good morning",
    ),
    "fr": (
        "bonjour",
        "merci",
        "salut",
    ),
    "it": (
        "ciao",
        "grazie",
        "buongiorno",
    ),
    "es": (
        "hola",
        "gracias",
        "buenos días",
        "buenos dias",
        "me gusta",
        "este idioma",
        "me gusta este idioma",
    ),
    "pt": (
        "olá",
        "ola",
        "obrigado",
        "bom dia",
    ),
    "de": (
        "hallo",
        "danke",
        "guten tag",
    ),
    "nl": (
        "goedemorgen",
        "dank je",
    ),
    "sv": (
        "hej hur",
        "hur mår du",
    ),
    "tr": (
        "merhaba",
        "teşekkür",
        "tesekkur",
    ),
    "be": (
        "добры дзень",
        "прывітанне",
        "гэта кароткі",
        "правяраем",
        "беларускай мове",
        "вызначэння",
        "вызначэння мовы",
        "мовы",
        "дзякуй",
        "калі ласка",
        "што",
        "гэта",
        "ёсць",
        "няма",
        "дзень",
        "беларус",
        "размаўляць",
        "чалавек",
        "жыццё",
        "краіна",
    ),
    "uk": (
        "привіт",
        "дякую",
        "будь ласка",
        "україн",
        "сьогодні",
        "немає",
        "мовою",
        "людина",
        "життя",
        "країна",
        "розмовляти",
    ),
    "ru": (
        "привет",
        "спасибо",
        "пожалуйста",
        "как дела",
        "сегодня",
        "здравствуйте",
        "человек",
        "жизнь",
        "страна",
        "говорить",
    ),
    "nb": (
        "bokmål",
        "bokmål i",
        "norsk bokmål",
    ),
    "nn": (
        "nynorsk",
        "korleis",
        "dette er ei",
    ),
    "hr": (
        "ovdje",
        "hrvatski",
        "hrvatska",
        "lijep dan",
        "dobar svijet",
    ),
    "bs": (
        "bosanski",
        "bosanska",
        "hvala",
        "molim",
        "pomoć",
    ),
    "sl": (
        "slovenskem jeziku",
        "preizkušamo",
        "preizkusamo",
    ),
    "ca": (
        "avui",
        "estas avui",
        "com estas avui",
        "aquest",
        "català",
        "catala",
    ),
    "sr": (
        "ovde",
        "srpski",
        "srpska",
        "govorimo srpski",
        "lep dan",
        "dobar svet",
        "srpska rečenica",
        "ovo je srpska",
    ),
    "da": (
        "hej hvordan",
        "hvordan går det",
        "hej hvordan går det",
    ),
}

EXACT_PHRASE_LANGUAGE_HINTS = {
    "hello": "en",
    "hi": "en",
    "friend": "en",
    "bonjour": "fr",
    "salut": "fr",
    "ciao": "it",
    "hola": "es",
    "olá": "pt",
    "ola": "pt",
    "hallo": "de",
    "hej": "sv",
    "merhaba": "tr",
}

SCRIPT_RULES = {
    "el": ("Greek", (0x0370, 0x03FF)),
    "hy": ("Armenian", (0x0530, 0x058F)),
    "ka": ("Georgian", (0x10A0, 0x10FF)),
}


def get_language_name(code):
    return LANGUAGE_NAME_BY_CODE.get(code, code)
